export const CLIENT_ROUTES = {
  home: '/',
  products: '/san-pham',
  productDetail: '/san-pham/:slug',
  combos: '/combo',
  workspace3d: '/workspace-3d',
  reviews: '/danh-gia',
  policies: '/chinh-sach',
  returnPolicy: '/chinh-sach/doi-tra',
  warrantyPolicy: '/chinh-sach/bao-hanh',
  paymentPolicy: '/chinh-sach/thanh-toan',
  shippingPolicy: '/chinh-sach/van-chuyen',
  contact: '/lien-he',
  cart: '/gio-hang',
  checkout: '/thanh-toan',
  account: '/tai-khoan',
  accountProfile: '/tai-khoan/thong-tin',
  accountOrders: '/tai-khoan/don-hang',
  accountOrderDetail: '/tai-khoan/don-hang/:id',
  accountPayments: '/tai-khoan/lich-su-thanh-toan',
  accountSettings: '/tai-khoan/cai-dat',
  login: '/dang-nhap',
  register: '/dang-ky',
  payosReturn: '/payment/payos/return',
  payosCancel: '/payment/payos/cancel',
}
